### ISSUE TITLE
Options page doesn't load when published

### ISSUE THREAD

**Issue by alexcroox** [fent/chrome-options#2]
This library works great locally, however when published the options page just outputs the following string:

`bower_components/chrome-options/options.html`

The source is here https://github.com/alexcroox/history-domain-scrubber

**Comment by alexcroox** [comment]
Okkk... my source shows that text. Well this is embarrassing...

**Comment by fent** [comment]
I'm getting the text as well after I installed it from the web store. But not when I cloned it. What method did you use to package it and upload it to the store?

**Comment by alexcroox** [comment]
Oh is this something to do with bower (which I’d not used before). I normally just highlight all files in folder and click create archive on OSX.

**Comment by fent** [comment]
What I did was use the `zip` command, but I'm not too sure that's different from compressing from the context menu.

    zip -r compressed_extension.zip history-domain-scrubber/

Or it may be an issue with the softlink. Could try using a hardlink instead for the `options.html` file

    ln -f bower_components/chrome-options/options.html

**Comment by alexcroox** [comment]
The hardlink worked thanks, published an update to the store and can use the options page now 👍

Thanks!
