### ISSUE TITLE
Example for access in Background.js

### ISSUE THREAD

**Issue by hevilp** [fent/chrome-options#3]
Hi,

thanks for the nice tool, but how do I access the options in background.js?
`chrome.options.addTab('General', [
{ name: 'login', type: 'text', desc: 'Login' },
  ], desc: 'Seitenauswahl' },
]);`

`chrome.storage.sync.get(function(items) {
});`?

So in general, how do I access my stored variables in content or background.js?

**Comment by fent** [comment]
See the `chrome.storage` API: https://developer.chrome.com/extensions/storage#type-StorageArea

So to get all options you would use

```js
chrome.storage.sync.get(null, function(items) {
});
```
