### ISSUE TITLE
HTML in desc of field

### ISSUE THREAD

**Issue by shamel67** [fent/chrome-options#5]
Putting HTML in the description of a field will render as text instead of HTML.

Example:
```
{
  name: 'myoption',
  desc: 'Lorem ipsum <strong>important</strong> <a href="http://somewhere.com">more info</a>.'
}
```

**Comment by fent** [comment]
I guess it does make sense to want to customize a description like that. I'll assign a label to this to know to work on it later.

For now if you really need it, could try using the [html type](https://github.com/fent/chrome-options#html)

**Comment by shamel67** [comment]
Here's what I will use:
```
{
    type: 'row',
    options: [{
      name: 'option',
      desc: 'Something',
      default: true
    }, {
      type: 'html',
      html: '<a href="https://somewhere.com/">More info</a>.'
    }
```
I also slightly adjusted the CSS:
```
.chrome-bootstrap .content div .suboptions.row {
  padding-left: 0px !important;
}
```

**Comment by shamel67** [comment]
Yes, it might be some additional formatting, links, an image, etc.
