### ISSUE TITLE
New feautre: hidden field

### ISSUE THREAD

**Issue by shamel67** [fent/chrome-options#8]
Small feature enhancement which makes it easy to set default values and maintain consistency for all configuration options:
In chrome-options.js, function chrome.options.addLabelNField() and chrome.options.base.checkbox()
+++
`option.hidden && $container.classList.add('hidden');`
+++

In chrome-options.css, add the following:
```
.chrome-bootstrap .hidden {
  display: none;
}
```

**Comment by fent** [comment]
Is the use case here setting up defaults for options that you'll set elsewhere?

**Comment by shamel67** [comment]
Yes, exactly, so this way I can initialize with some default values without showing them to the user. And it's easier this way since I can keep all options in one place.
